Repository Homebrew/homebrew-linux-dev, pull requests merged in 2020-11, with the labels that each got.

#185 migrate-formula: Fix three bugs
  cmd/migrate-formula.rb
Labels: bug, needs response

#186 wheezy: install pgrep for brew
  Dockerfile
Labels: needs response

#188 Fix announce: args.resolved_formulae is deprecated
  cmd/announce.rb
Labels: bug
